aws_region           = "us-east-1"
environment          = "prod"
domain_name          = "rithivilasartsandcrafts.com"
bucket_name          = "rithi-vilas-arts-crafts-prod"
hosted_zone_id       = "Z0829280101Q736X67ZDG"
tf_state_bucket      = "rithi-vilas-tf-state"
