---
app_name: rithi-vilas-arts-and-crafts
aws_region: us-east-1
s3_bucket: "{{ lookup('env', 'S3_BUCKET_NAME') }}"
cloudfront_distribution_id: "{{ lookup('env', 'CLOUDFRONT_DISTRIBUTION_ID') }}"
build_dir: dist
